### ISSUE TITLE
JsBin examples are broken in Chrome

### ISSUE THREAD

**Issue by lhorie** [cyclejs/cyclejs.github.io#45] opened 2016-01-20 20:58 UTC
Repro steps: Open any page w/ a JsBin example, e.g. http://cycle.js.org/basic-examples.html

Expected: not a blank jsbin

Actual: blank jsbin and errors on console

```
Uncaught SecurityError: Failed to read the 'frame' property from 'Window': Blocked a frame with origin "http://jsbin.com" from accessing a frame with origin "http://cycle.js.org". Protocols, domains, and ports must match.
```

```
babel is not defined
```

**Comment by ashleyconnor** [comment] 2016-01-20 22:02
I'm also getting this.

**Comment by staltz** [comment] 2016-01-21 07:31
Duplicate of: https://github.com/cyclejs/cyclejs.github.io/issues/24

TL;DR: Chrome or JSBin's fault.

**Closed by staltz** 2016-01-21 07:31 UTC
